### ISSUE TITLE
VAN: validation should be optional for upsert_person

### ISSUE THREAD

**Issue by kbenker** [move-coop/parsons#10]
When you pass a record to `upsert_person`, it validates that "the minimum combination of fields were passed." The VAN API doesn't actually reject records without this info; it will just always create new records if there's insufficient info to match on. 

I understand that some users may want this validation to avoid adding duplicates, but others may still want to add new records for people they have sparser information on.

**Comment by jburchard** [comment]
@ydamit - FYI

**Comment by jburchard** [comment]
@kbenker So is there any minimum number of fields?
