### ISSUE TITLE
[Bug] Parsons 3.1.0 targets yanked 4.0.0 version of braintree with critical bugs

### ISSUE THREAD

**Issue by bmos** [move-coop/parsons#1007]
Parsons 3.1.0 depends on braintree 4.0.0 which has been yanked due to critical bugs.

## Detailed Description

When I install parsons 3.1.0 via pip, I get this message:
> WARNING: The candidate selected for download or install is a yanked version: 'braintree' candidate (version 4.0.0 at https://files.pythonhosted.org/packages/a5/1e/641306eec960161028e0a30d2f635abdfbdb89029330df1701bc106e5d8c/braintree-4.0.0-py2.py3-none-any.whl (from https://pypi.org/simple/braintree/))
Reason for being yanked: critical bugs

When I install it via [uv](https://github.com/astral-sh/uv) it doesn't even install for the same reason.

## To Reproduce

Create a new virtual environment and run `pip install parsons==3.1.0`

## Your Environment

* Version of Parsons used (if you know): **v3.1.0**
* Environment name and version (e.g. Chrome 39, node.js 5.4): 
* Operating System and version (desktop or mobile): **Pop!_OS 22.04 LTS**

## Additional Context

In a fork I'm playing around with, braintree==4.26.0 and google-cloud-bigquery==3.18.0 were needed to get pytests passing. I'm not sure why that isn't the case on this repo but it seems like these versions might be safe to update.

## Priority

For me it's low because I don't use braintree but "critical bugs" makes it sound rather serious for people who use that integration.

**Comment by shaunagm** [comment]
Fixed in #1054
