### ISSUE TITLE
[Feature/Addition] Compatibility for Python 3.12

### ISSUE THREAD

**Issue by crayolakat** [move-coop/parsons#1021]
## Detailed Description
Provide compatibility for Python 3.12, the latest minor release of Python. Currently, Parsons is compatibility up to and including Python 3.10. #1012 brings the compatibility up to and including 3.11, but has not been merged into the `main` branch or released yet.

## Possible Implementation
Update to Python 3.12 and test to see if anything breaks or is now incompatibile.

## Priority
Low priority

**Comment by shaunagm** [comment]
Hi @crayolakat! In testing we discovered that PETL does not yet support 3.12, this is a crucial dependency so until PETL updates, we're stuck. Once they've updated, we can circle back and support 3.12

**Comment by crayolakat** [comment]
Ok, thanks for looking into this!

**Comment by jdw25** [comment]
@shaunagm -- does [this answer](https://github.com/petl-developers/petl/issues/664) and [this addition of 3.12 into PETL CI testing](https://github.com/petl-developers/petl/pull/659) mean we we can now consider support for 3.12 _not blocked_ by PETL?   

I think supporting Python 3.12 would be beneficial --  3.12 is the default install for Ubuntu 24 LTS (which is the latest-greatest LTS Ubuntu release)

**Comment by shaunagm** [comment]
Yes, you're right @jdw25 that PETL is not a blocker. So next step is for someone to open a PR adding 3.12 to our test suite in github actions, and see if everything passes (plus add it to our docs & readme & setup.py as well). If it does, adding 3.12 support is as simple as merging, otherwise we'll have additional work to do.

**Comment by jdw25** [comment]
This should now be complete with https://github.com/move-coop/parsons/pull/1087

**Comment by shaunagm** [comment]
Thank you @jdw25!
