### ISSUE TITLE
Connection Error in the Person class

### ISSUE THREAD

**Issue by cherdeman** [move-coop/parsons#103]
Hi there,

I found an error in the People class in the `people.py` file.  I got the following error when trying to use the find_people method: `'VAN' object has no attribute 'post_request'`. It looks like this is because it is calling the `get_request` and `post_request` methods from the VANConnector class on the VAN class. 

I think the simplest fix may be to change the People constructor to:

```
class People(object):

    def __init__(self, van_object):

        self.connection = van_object.connection
```

So that `self.connection` in the People class refers to the VAN connection object rather than the VAN object.

**Comment by jburchard** [comment]
Thank you for this.

Do you mind posting the full stack trace on this so that we can dig into it?

**Comment by cherdeman** [comment]
This is from running the `get_person` method with a VANID:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f2e7b0701390> in <module>()
----> 1 people.get_person('108793136')

~/Bernie/Bernie/lib/python3.6/site-packages/parsons/ngpvan/people.py in get_person(self, id, id_type, fields)
    193 
    194         logger.info(f'Getting person with {id_type} of {id}')
--> 195         return self.connection.get_request(url, params={'$expand': fields})
    196 
    197     def apply_canvass_result(self, id, result_code_id, id_type='vanid', contact_type_id=None,

AttributeError: 'VAN' object has no attribute 'get_request'
```

**Comment by cherdeman** [comment]
False alarm - I was separately instantiating the a Person object unnecessarily. When I make the call from a van object it works as intended. Thanks for your quick response!

**Comment by jburchard** [comment]
No worries. Glad that it ended up working out. I know that some of the classes in the documentation can be a little bit confusing.
