### ISSUE TITLE
Remove md5 security workaround after dropping 3.8

### ISSUE THREAD

**Issue by bmos** [move-coop/parsons#1138]
Resolving one of bandit's flagged security issues required [adding an if/else statement](https://github.com/move-coop/parsons/commit/01ef28b856ce9126a16e06b486764d70d6ab1ff3) that can be reverted once we drop support for python 3.8.

**Comment by DCRepublic** [comment]
I'd like to work on this, however the commit you linked doesn't seem to exist.

**Comment by bmos** [comment]
This bug is actually relating to code that has not been merged yet, but I was asked to post it here. Python 3.8 should be dropped in December or early next year.
