### ISSUE TITLE
Onboarding Process

### ISSUE THREAD

**Issue by AnthonyMartinez** [move-coop/parsons#118]
Hey! I mentioned this on the previous week's webinar but am now just making an Issue about it. 

## Problem
Parsons has a very important goal of lowering the barrier for people who wouldn't typically contribute to project or consider themselves technical enough to use parsons. I think that if we are trying to dramatically increase the amount of parsons users and contributors, then we need to focus more on the problems people encounter before they even make it to using parsons in their code- things like (speaking from very specific personal experience) how do I set up a development environment? 

## Proposed solution
I need at least one other collaborator to make a short guide on how to go from a place of knowing very little code (but having a lot of motivation to do something cool) to getting an environment set up and ready to use parsons (as in pip installing and ready to REPL some .py) and then building a small "hello world" type script using a feature (maybe something like splitting a large file into specific chunks, or turning json to csv- ideally something practical that real world people are always trying to do but are actually really straightforward to do in parsons).

I'm more than happy to take the lead on this but I would need help in splitting up this work for it to happen on a realistic timeline and be good enough to be useful.

**Comment by elyse-weiss** [comment]
@ydamit can you send Anthony some of what we have from our Parsons bootcamp?

@eliotst eager for you to correct me if I'm wrong, but I think we should create some sort of flow chart where you try to install WITHOUT virtual environments and only then set up a virtual environment if you run into trouble (or just plain want one!). I don't think a beginner user needs a virtual environment.

**Comment by eliotst** [comment]
@elyse-weiss Nothing to correct. As you say, I think we could describe a "simple install" where the user doesn't use a virtualenv, but where we highlight issues they might run into and explain why they might need a virtualenv. Then, we could have a more advanced install for users who run into issues, or as you say, just want one.

**Comment by AnthonyMartinez** [comment]
Hi all! Hope everyone had a nice holidays. Slowly picking things up from before the break:

1. would love to look over any materials from parsons bootcamp! If anyone is opinionated about any sort of technical pedagogy, would also love to listen. 
2. not needing to go over virtualenv makes sense. I do think though that the flowchart should be a little explanatory about why python versions are important e.g. if youre going off an old tutorial, you could run into problems from unintentionally coding in python 2.
3. i can throw up a quick planning/brainstorming doc with some common things that we can work to address, will update here with the link by the end of the weekend.

**Comment by elyse-weiss** [comment]
Hey @AnthonyMartinez - @ydamit added a `useful_resources` folder to Parsons with a lot of our internal bootcamp materials. Can you check it out then use #3 above to address what is missing?
