### ISSUE TITLE
Create Rock The Vote Class

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#119]
We have code in the TMC private repo, and can probably easily create a class.

h/t to Gerard at ACRONYM who I originally stole said code from.

**Comment by asonntag** [comment]
Leaving a comment here as suggested by @eliotst 

My use for this is somewhat undefined, atm. Essentially, we're not really happy with the reports interface provided by Rock the Vote and stakeholders want to look at something else. We'll probably end up making a Tableau report with whatever data we're able to grab. We should be able to get what we need without using Parsons. But, I figure if there's code out there that might help, I'll take it!
