### ISSUE TITLE
s3.transfer_bucket - document that original file is not removed from original bucket

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#122]
Documentation should be clear here.

**Comment by jburchard** [comment]
Should we rename the method to be `s3.copy_bucket()` instead? That seems to be more descriptive of what's going on.

**Comment by elyse-weiss** [comment]
My only objection is I know both Martha and I have used `transfer_bucket()` in a number of scripts, and I think to avoid breaking things we should avoid changing names of functions.

We could add a parameter to allow folks to delete from original bucket if they want?

**Comment by elyse-weiss** [comment]
other proposal: add parameter as to whether to drop from original bucket

**Comment by eliotst** [comment]
One thing to pay attention to here is permissions around being able to delete objects.
