### ISSUE TITLE
Custom Fields endpoints in Parsons VAN

### ISSUE THREAD

**Issue by ydamit** [move-coop/parsons#171]
VAN charges to add custom fields into Pipeline. Meanwhile, custom fields can be crucial to EveryAction use-cases, and loading a value to a custom field on a person record requires not only the field's numeric ID, but also its group's. Rather than requiring a sync's end users to have to find and submit both IDs as parameters, a single call to get all custom field data would allow comparison to a submitted custom field ID (or even custom field name).

**Comment by jburchard** [comment]
Addressed in #173
