### ISSUE TITLE
Redshift: DIST/SORT key nudge.

### ISSUE THREAD

**Issue by jburchard** [move-coop/parsons#195]
We should include a logger warning in the Redshift copy that alerts the user is there is not a DIST/SORT key association with their copy statement. This could nudge folks towards utilizing Redshift best practices.

**Comment by eliotst** [comment]
I think this should just be a matter of adding an `if` check at the top of the `Redshift.copy` method to check for values for the optional distkey and sortkey params.

**Comment by ibrand** [comment]
Hey @jburchard and @eliotst ! I'd be interested in picking this up, but I'd love a little more background here. I'm assuming that "Redshift copy" refers to `parsons/databases/redshift/rs_copy_table.py` ? But it might referring to a different area of code. Is that the right idea?

**Comment by eliotst** [comment]
Hey @ibrand ! Sorry for the delayed response. If you're still interested in picking this up, we would love your help.

The `copy` method is in the `Redshift` class in `parsons/databases/redshift/redshift.py`. `copy` uses the `copy_statement` method of the `RedshiftCopyTable` class in `parsons/database/redshift/rs_copy_table.py` under the hood, but the `distkey`/`sortkey` handling is actually done before the `copy_statement` is invoked . I think the solution here could just be a matter of logging a message if the `distkey` and `sortkey` arguments aren't passed (are `None`) to the `copy` method.

There is also a `copy_s3` method in the `Redshift` class in `redshift.py` that works similarly to `copy` (except it takes an S3 bucket / key as opposed to a Parsons `Table` as an argument). Both `copy_s3` and `copy` in the `Redshift` class should be updated.

**Comment by tiburona** [comment]
Hey @eliotst , what's the status of this?  I could pick it up.

**Comment by jburchard** [comment]
Up for grabs! That would be great!

**Comment by tiburona** [comment]
Ok, I'm taking it.  I'll let you know if questions come up but I see you provided a lot of context in a previous comment.
