### ISSUE TITLE
ActionKit Updates

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#233]
This issue is for building out functions to update events and signups in the ActionKit class. API documentation for these is:

- [Updating an event](https://roboticdogs.actionkit.com/docs/manual/api/rest/examples/updateevent.html)
- [Updating a signup](https://roboticdogs.actionkit.com/docs/manual/api/rest/examples/updatesignup.html)

**Comment by rgriff23** [comment]
Can I work on this?
