### ISSUE TITLE
Add Bloomerang class

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#266]
This ticket is for adding a Bloomerang class to Parsons.

[API documentation is here.](https://bloomerang.co/features/integrations/api/rest-api/)

The most important capabilities will be:

- Pull constituents and their emails, addresses, and phone numbers
- Pull donations, recurring donations, recurring donation payments, pledges, and pledge payments
- Pull custom fields and custom field values
- Create & update constituents
- Create donations, recurring donations, and recurring donation payments
- Create interactions

**Comment by rgriff23** [comment]
I'll take this one on if that's alright. I won't have API access, so I can't do a complete testing.

**Comment by mkwoods927** [comment]
Adding more specifics on what methods would be helpful here! Methods to pull lists in addition to individual records would definitely be helpful.

In terms of constituents and contact info, it looks like get/constituent and get/constituents both return the primary e-mail, primary phone, and custom fields and values, so it's not a high priority to create separate methods for those. I don't think address gets returned though, so get/addresses would be useful!

For transactions, both get/transactions and get/transactions/designations are valuable. The first gives some basic info, while the second provides more detail like custom field data, campaign, and fund.

**Comment by rgriff23** [comment]
> In terms of constituents and contact info, it looks like get/constituent and get/constituents both return the primary e-mail, primary phone, and custom fields and values, so it's not a high priority to create separate methods for those. I don't think address gets returned though, so get/addresses would be useful!

It actually looks like PrimaryAddress (with street, city, state, etc) is a field returned for constituents: https://bloomerang.co/features/integrations/api/rest-api#/Constituents/get_constituent__id_

**Comment by mkwoods927** [comment]
Oh great, then no need to make a separate method!

**Comment by shaunagm** [comment]
Closing this as the class was created by https://github.com/move-coop/parsons/pull/337. Any enhancements should be in their own issue. Thanks again, Randi!
