### ISSUE TITLE
utilities.files.has_data produce True if only header row

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#267]
Ideally this would be False if there was only a header. Perhaps we could add an argument determining if one should look for a header or not?

**Comment by jburchard** [comment]
This method doesn't actually open the file, so I'm hesitant to add this as a parameter.

It merely looks to see if the size if `> 0` bytes. 

I think that the answer to this might be a separate convenience method that checks if a CSV has any rows in it. What do you think @elyse-weiss?

**Comment by elyse-weiss** [comment]
Yeah, this all makes sense. I'll close!
