### ISSUE TITLE
Improve contributor onboarding

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#286]
Highest Priority:

- [x] move contributing.md file to the top level directory
- [x] update contributing guide to link to useful_resources, not sample_code folder (must have gotten moved)
- [x] contributing.md should have clear walkthrough of steps, including cloning from github, setting up a virtualenv, up through running tests when they've finished installing
- [x] contributing.md (and maybe also readme.md) should include links to communications channels so people know how to talk to us, where to ask for help, how to report bugs, feature requests, etc
- [x] quickstart guide needs to not require creating accounts, setting env variables, etc.  need to pick a connectorwhere we can create a dummy account (or the API itself provides a dummy endpoint) that we can use here.
- [x] add instructions for building the docs (see https://github.com/move-coop/parsons/pull/313#issuecomment-660397875)

Lower Priority:
- [x] add "capitalize Parsons" to best practices in contrib docs
- [ ] contributing.md file should provide extra context/explanations for things that might be new to people, beyond just "run this command"
  - unit testing & what they should see when they run pytest
  - setting up a virtual environment
  - the difference between installing via pip and setting up as a developer (cloning, etc)
- [ ] we should make sure install is testing on Windows and Linux as well as Mac, and it's clear what people on those platforms need to do differently, if anything
- [ ] look into adding install instructions for Anaconda users

**Comment by ehrenfoss** [comment]
I'm new to parsons and I'd like to help with this. I'm on Windows, and I have some Salesforce experience and can look into dummy account / developer account creation from the command line.

**Comment by shaunagm** [comment]
That would be great, @ehrenfoss!  It looks like the authentication guide is the main thing the Salesforce docs need, although if you could update the quickstart guide to show the salesforce connector class being initialized with an environmental variable that'd be great too.  !

**Comment by shaunagm** [comment]
Oh, sorry @ehrenfoss, I think I slightly misunderstood and thought you were responding to this issue (https://github.com/move-coop/parsons/issues/269) and offering to update the Salesforce connector docs.  If Salesforce does allow dummy accounts it would be a great choice for the quickstart guide.

**Comment by pjsier** [comment]
Some additional guidance on how to format the docstrings would be useful. It looks like they might be following [Google's style guide](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings), and if they are stating that explicitly and linking to the document would probably solve that.

Otherwise I think some more clarity on things like whether arguments and return values are followed in the same line by their type with a description below or just a description in the same line would be helpful (i.e. `name: str` vs `name: Name of the argument`). The arguments mostly seem to include the type on the same line, but it looks like the return values alternate between a text description alone and the return type with a description indented on the next line.

**Comment by ehrenfoss** [comment]
I started [my fork here](https://github.com/ehrenfoss/parsons). Some questions:

- Is there any desired naming convention for the forks? 
- Any syntax we should use with commit messages so they are linked to issues properly? Like the issue #?

Also, I'm on Windows, and with `python setup.py develop` I'm hitting an issue with psycopg. Happy to make a separate thread for this. Details:

`Running psycopg2-binary-2.7.6.1\setup.py -q bdist_egg --dist-dir C:\Users\ehren\AppData\Local\Temp\easy_install-b8p3sfdl\psycopg2-binary-2.7.6.1\egg-dist-tmp-8jljr8wg
psycopgmodule.c
psycopg\psycopgmodule.c(689): error C2037: left of 'next' specifies undefined struct/union '_is'
psycopg\psycopgmodule.c(690): error C2037: left of 'next' specifies undefined struct/union '_is'

It appears you are missing some prerequisite to build the package from source.`

I tried `pip install psycopg2-binary`, which succeeds, but re-running `python setup.py develop` again fails. However, attempting to use the psycopg2 import seems to work fine. Once I comment out psycopg2 in requirements.txt the rest of the setup finishes fine.  

That's as far as I got - next step would be to poke at what C compiler I have. If anyone else has encountered this, let me know?

**Comment by shaunagm** [comment]
Sorry I didn't see this before now, @ehrenfoss!  I need to reconfigure my Github notifications somehow, I guess.

@eliotst can tell us if there are any naming conventions for the forks or syntax for the commit messages.  

re: the psycopg2 thing - I don't know if it's a known issue in Parsons, but I've run into problems with psycopg2 on other projects.  Probably worth creating a separate issue for but again let's wait for @eliotst for his opinion on that, maybe it's a simple fix.

**Comment by shaunagm** [comment]
Also @ehrenfoss your other changes look great - please go ahead and submit a PR for them and we'll merge them.  :)

**Comment by ehrenfoss** [comment]
Added PR for item #6 in the high priority section (building docs) https://github.com/move-coop/parsons/pull/318

**Comment by SorenSpicknall** [comment]
This is generally out of date, so closing.
