### ISSUE TITLE
Add phoneOptInStatus to VAN.upsert_person()

### ISSUE THREAD

**Issue by erictnelson** [move-coop/parsons#287]
Include the option to set phoneOptInStatus when upserting a person into VAN.

For organizations using Frakture (and possibly other) tools to sync data out of VAN/EA, this field is necessary to determine which records/phone numbers can be synced.

**Comment by eliotst** [comment]
As a workaround, people can make use of the `upsert_person_json` method on the VAN Connector, which provides a more extensive / flexible API for updating people data.
