### ISSUE TITLE
Build SurveyGizmo Class

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#297]
TMC wrote some code that we know works: https://gist.github.com/elyse-weiss/101d251eeed2e4f2fb25e8754ca493bd

Eager to finalize as Parsons connector.

**Comment by coreyhaines** [comment]
Have started converting it over. Need to write tests for the functions there.

**Comment by shaunagm** [comment]
Addressed in https://github.com/move-coop/parsons/pull/354
