### ISSUE TITLE
Hustle: Create A Simple Global Opt Out Method

### ISSUE THREAD

**Issue by jburchard** [move-coop/parsons#30]
My suspicion is that this is going to be a pretty common use case. The idea is to be able to pass in a phone number and add it to the global DNC list.

**Comment by elyse-weiss** [comment]
The Hustle endpoint for this does not exist. Will reach out to Hustle on this.

**Comment by elyse-weiss** [comment]
We can do this in `updated_lead`. No need for separate call.
