### ISSUE TITLE
Add connector account creation information to documentation

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#312]
We want to add information for each connector about whether they offer free accounts that you can use to authenticate the connector, as well as whether they offer a dummy/public API (where you wouldn't even need to authenticate).  There's also a column which contains an evaluation of the effort involved in creating a Parsons-specific dummy account with shared/open credentials.  

The table below can be updated as we research the different connectors, and then once we're ready we'll move this to the sphinx docs.  In addition to a "yes/no", a link to where you found that information would be much appreciated.

| Connector | Has Free Accounts | Has Public API | Can Create Parsons Dummy Account| 
| -------------- | :--------- | ----------: | ----------: | 
| Action Kit
| Action Network
| Airtable | [yes](https://airtable.com/pricing) | no | yes |
| AWS: Lambda
| AWS: S3
| AWS: Redshift | No | No | Ragtag has an account, please ask for access |
| Azure: Blob Storage
| Bill.com
| Braintree
| Civis
| Copper
| CrowdTangle
| Databases: MySQL
| Databases: Postgres
| Databases: Redshift
| Databases: Database Sync
| Facebook Ads
| FreshDesk
| Google: Big Query
| Google: CloudStorage
| Google: Civic
| Google: Google Sheets
| Hustle
| MailChimp
| Mobilize America
| New/Mode
| Ngpvan | No | No | Ragtag has an account, please ask for access |
| PDI
| Phone2Action
| Redash
| Rock the Vote
| Salesforce | [yes](https://developer.salesforce.com/signup) | [yes](https://developer.salesforce.com/docs/api-explorer) | [yes](https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm)
| SFTP
| TargetSmart
| Twilio
| TurboVote
| Zoom

**Comment by ehrenfoss** [comment]
@shaunagm Salesforce

* Offers free developer accounts: https://developer.salesforce.com/signup
* There's a suite of Salesforce DX and Salesforce CLI tools, I've recently used them with Visual Studio Code. 
* Scratch orgs are 'disposable' Salesforce instances that can be used for unit tests, development, etc. https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_scratch_orgs.htm

**Comment by shaunagm** [comment]
@ehrenfoss sorry for the delay responding!  Thanks for researching this, I've added your answers to the box above.  This information doesn't need to go into `docs/salesforce.rst` but taking a look at the connector docs it *does* need some improvements - in particular, it needs an authentication blurb (see [action kit's](https://move-coop.github.io/parsons/html/action_kit.html) for a good model) as well as another sentence or two explaining what Salesforce is.  The Salesforce quickstart should also provide information about how to use the authentication info when instantiating the connector (the Actionkit connector docs do this well too).

**Comment by shaunagm** [comment]
Closing this as we now have this information in our docs (see [here](https://move-coop.github.io/parsons/html/build_a_connector.html#sandbox-access). I included some of the remaining info from the table above in [this PR](https://github.com/move-coop/parsons/pull/638). There's definitely connectors for us to create sandboxes for, but folks can request that via the Parsons Slack or leaving a comment here.
