### ISSUE TITLE
Load CSV data from an S3 manifest

### ISSUE THREAD

**Issue by eliotst** [move-coop/parsons#319]
Redshift uses [manifest files](https://docs.aws.amazon.com/redshift/latest/dg/loading-data-files-using-manifest.html) when loading data from S3 (using `COPY`) and when exporting data into S3 (using `UNLOAD`). It could be useful to have a method on the `S3` class that would be able to load multiple CSV files from S3 into a single `Table`.

Under the hood, the method would just need to:
  1) download the manifest file from S3
  2) use the manifest to figure out which files to grab from S3
  3) load each of the files into a `Table`
  4) concatenate all of the files into a single `Table`

**Comment by johnarky** [comment]
Unless dannyboy15 will be assigned, I'd like to do this.
Is there any problem with the manifest?
Do the files to be concatenated have the same columns?  Is this a concern for Parsons?

**Comment by shaunagm** [comment]
Status of issue: @dannyboy15 is working on this.

**Comment by dannyboy15** [comment]
I think we can close this issue since the PR was merged.
