### ISSUE TITLE
Better documentation for Parsons Table

### ISSUE THREAD

**Issue by coreyhaines** [move-coop/parsons#382]
While working on some scripts using the `SurveyGizmo` connector, we found that it was difficult to find what functionality was available on `Table`.

Converting to/from a `Table` is nicely discoverable

![image](https://user-images.githubusercontent.com/3962/92779436-ac880d80-f367-11ea-9888-f35ce050bc9b.png)

But if we are looking for functions on how to manipulate them, then there isn't an equivalent list like this, so you have to scan through a list, and it is hard to scan. For example, using the ETL functionality 

![image](https://user-images.githubusercontent.com/3962/92779911-16a0b280-f368-11ea-9ef4-74ce8a282a80.png)

Would be awesome to have a scannable list for the different objects, similar to the summary lists for to_/from_ functions.

**Comment by jburchard** [comment]
Would something like this work?

![image](https://user-images.githubusercontent.com/5530043/92947952-4d390480-f41e-11ea-8f8e-a0117597a92d.png)

**Comment by coreyhaines** [comment]
Really great. Thanks!

**Comment by shaunagm** [comment]
Thank you @jburchard!
