### ISSUE TITLE
Add missing import information to How to Build a Connector doc

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#416]
The [How to Build a Connector](https://move-coop.github.io/parsons/html/build_a_connector.html) doc currently doesn't remind the user to hook up the connector to Parson's quirky import system.  See [this comment](https://github.com/move-coop/parsons/issues/217#issuecomment-698567117) (step 1) for the missing information.

**Comment by davidpablocohn** [comment]
I can take this one.

**Comment by shaunagm** [comment]
Thanks for offering, @davidpablocohn! Do you mind if we hold onto it for someone for whom it would be their first issue?

**Comment by davidpablocohn** [comment]
That sounds like a fine idea!

I notice there's some broken stuff in the formatting of that doc as well.
I'll go ahead and leave that, but add notes to the issue as guidance for
whomever hops onto it.

**Comment by davidpablocohn** [comment]
Some other things about the doc that could use a little attention:

```
/opt/ragtag/parsons/docs/build_a_connector.rst:245: WARNING: Inline literal start-string without end-string.
/opt/ragtag/parsons/docs/build_a_connector.rst:245: WARNING: Inline interpreted text or phrase reference start-string without end-string.
/opt/ragtag/parsons/docs/build_a_connector.rst:272: WARNING: Block quote ends without a blank line; unexpected unindent.
/opt/ragtag/parsons/docs/build_a_connector.rst:272: WARNING: Inline literal start-string without end-string.
/opt/ragtag/parsons/docs/build_a_connector.rst:272: WARNING: Inline interpreted text or phrase reference start-string without end-string.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] zoom                                                                                              
/opt/ragtag/parsons/docs/build_a_connector.rst:36: WARNING: Could not lex literal_block as "python". Highlighting skipped.
/opt/ragtag/parsons/docs/build_a_connector.rst:54: WARNING: Could not lex literal_block as "python". Highlighting skipped.
```

It looks like the doc is trying to use a triple-backquote for code instead of the rst directive ``.. code-block:: python`` used elsewhere in the docbase.

Also, given the length of the doc and its internal structure, I think it could benefit from a ``.. contents::`` directive right before "Getting Started"

**Comment by shepardjma** [comment]
I will work on this update.
