### ISSUE TITLE
Fix "note" display in VAN connector docs

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#426]
The formatting of some of the note displays in the VAN connector are off.

This is what it looks like:

![Screenshot from 2020-10-01 16-47-43](https://user-images.githubusercontent.com/1179362/94861658-dfbd3a00-0405-11eb-992b-7a6d5ee7366f.png)

This is what it should look like:

![Screenshot from 2020-10-01 16-47-29](https://user-images.githubusercontent.com/1179362/94861682-e946a200-0405-11eb-8037-bb345fc323aa.png)

If whoever fixes this skims through the other connectors looking for similar problems, that'd be great, but just fixing the VAN connector may be enough.

**Edited to add**: it looks like the notes also reference an `email_address` variable but the docstrings only mention an `email` parameter, we should check which is valid.

Another issue to fix with the VAN docs ("support" misspelled, plus sentence without ending):

![Screenshot from 2020-10-01 19-10-02](https://user-images.githubusercontent.com/1179362/94872129-cb833800-0419-11eb-94c8-c5ef7f8413a3.png)

**Comment by shaunagm** [comment]
Another issue with the VAN docs to fix - `apply_activist_code` and `remove_activist_code`, the docstrings say it takes a parameter `action` but neither does. (I suspect they used to be a single function that took an `action` param to distinguish, but now that there's both `apply_activist_code` and `remove_activist_code` it's unnecessary.

**Comment by rdhyee** [comment]
@shaunagm I'm willing to take on this issue. Please assign to me.

**Comment by Tomiiwa** [comment]
Hi, I'd like to work on this issue

**Comment by shaunagm** [comment]
That would be great, @Tomiiwa! Assigning you now.

**Comment by Tomiiwa** [comment]
Hi, I am seeing different results with the same search parameters. Which file exactly is the VAN Connector docs?

**Comment by shaunagm** [comment]
Here's the file: https://github.com/move-coop/parsons/blob/master/docs/ngpvan.rst

That said, I think the issue might be in the formatting of the docstrings linked in that file. The autodocs (auto-generated docs) probably require a syntax that is off for some methods like `upsert_person`. So you will probably need to edit some of the doc strings in these files: https://github.com/move-coop/parsons/tree/master/parsons/ngpvan

**Comment by Tomiiwa** [comment]
Got it, thanks
