### ISSUE TITLE
Make sure examples in docs are valid Python

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#430]
I noticed that some of the scripts in [this docs page](https://move-coop.github.io/parsons/html/table.html#parsons.etl.etl.ETL.coalesce_columns) are not valid Python - in particular, they're using non-strings as dictionary keys, for example:

![Screenshot from 2020-10-06 15-45-21](https://user-images.githubusercontent.com/1179362/95252436-fb9c5380-07ea-11eb-8869-a374b23184bf.png)

While this would be valid in Javascript, it's not in Python, and we don't want to mess anyone who is copying and pasting from the docs.  We should fix this and maybe also do a sweep of the docs to find and fix other examples.

**Comment by ndelrossi7** [comment]
Happy to work on this!

**Comment by SorenSpicknall** [comment]
Closing since the relevant documentation has since changed significantly.
