### ISSUE TITLE
Turn off No Disktey/Sortkey Alert on append and truncate

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#439]
Right now, if you use `to_redshift(..., if_exists='append')` you get an alert related to distkey and sortkey on COPY, which is irrelevant. We should turn it off if `if_exists` is append or truncate.

**Comment by jburchard** [comment]
I think that this was fixed in #402. Is it still happening?

**Comment by elyse-weiss** [comment]
Oh great! Will close.
