### ISSUE TITLE
Deal with dependent views and alter_table()

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#440]
You cannot run an alter_table if there are dependent views.

**Comment by dannyboy15** [comment]
I may be able to help with this. Do you have additional details, I wasn't able to find an `alter_table()` method.

**Comment by elyse-weiss** [comment]
hey @dannyboy15 - `alter_table` is within `copy`. It's used for extending varchar length where necessary. However, if there are dependent views, it fails. My thought was to maybe create `alter_table_cascade` and if that is used, it would drop dependent views?
