### ISSUE TITLE
Additions to Zoom class

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#459]
It would be helpful to add the following to the Zoom class:

- [get meeting registrants] (https://marketplace.zoom.us/docs/api-reference/zoom-api/meetings/meetingregistrants)
- [get webinars] (https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinars)
- [get webinar participants] (https://marketplace.zoom.us/docs/api-reference/zoom-api/reports/reportwebinarparticipants)
- [get webinar registrants] (https://marketplace.zoom.us/docs/api-reference/zoom-api/webinars/webinarregistrants)

**Comment by bzupnick** [comment]
I wrote a PR addressing this issue! 

It's my first PR here and I wasn't exactly sure how to test it. I followed the API from the docs you sent, and added tests accordingly with the example responses from the docs, but in regards to actually interfacing with Zoom that's not tested.

**Comment by mkwoods927** [comment]
Thank you @bzupnick !!
