### ISSUE TITLE
Creation of an Action Builder class

### ISSUE THREAD

**Issue by beckz0rz** [move-coop/parsons#473]
Action Builder is currently redoing their API, so this would be pending that

Right now, the only way to upload new data to Action Builder is to manually do it via a CSV upload

I would like for that to be easier!

I (Rebecca @ DSA) am happy to intro folks to Martha Grant to make this easier!

**Comment by SorenSpicknall** [comment]
If we could get access to the API when it's ready, this would be a great one for a volunteer to take on. I'll add some tags to reflect that.

**Comment by shaunagm** [comment]
We did a poll on new connectors in the Slack and Action Builder was the most desired, so labeling this as "high priority".
