### ISSUE TITLE
Add Params to Bloomerang Class

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#476]
Hello! I have a fairly urgent need to use the Bloomerang class, and would LOVE if someone could help me out by adding some additional parameters.

For the functions that loop through pages - `get_constituents`, `get_transactions`, `get_transaction_designations`, I would love to add:
- [ ] orderBy
- [ ] orderDirection
- [ ] lastModified (only relevant for constituents)

I know @rgriff23 was the original author!

**Comment by marikobriggs** [comment]
Hi, I'd love to take a shot at this!

**Comment by elyse-weiss** [comment]
hey @marikobriggs! sounds like @dannyboy15 is also interested in helping. I'm working on getting an API key for a sandbox for y'all to work with.

**Comment by dannyboy15** [comment]
Here's the PR I'm working on, #477. If we are able to get sandbox keys I can test the API, the local tests passed.

**Comment by elyse-weiss** [comment]
@dannyboy15 hero status! will likely test tomorrow morning if we don't get keys for you by then
