### ISSUE TITLE
DB Sync use source table schema to build schema for destination table

### ISSUE THREAD

**Issue by eliotst** [move-coop/parsons#481]
Right now, the DB sync classes leans on the `copy` function to create destination tables during a sync. So, the first chunk of data loaded into the destination is used to determine the table schema. However, if data from another chunk differs from the first chunk (e.g. longer/bigger values in columns), the db sync can fail.

Ideally the DB sync would reflect on the schema of the source table and use that to determine the schema for the destination table.

**Comment by jburchard** [comment]
I think that I can take this one.

**Comment by jburchard** [comment]
Addressed in #492.
