### ISSUE TITLE
rs.upsert alter_table not working 

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#493]
I have noticed this a few times over the last few weeks.

Code I am running:
```
rs.upsert(tbl, "mvp_bloomerang.constituents_PrimaryAddress", primary_key = 'id', 
          vacuum=False, distinct_check=True, cleanup_temp_table=False, alter_table=True)
```

Relevant error:
```
InternalError_: Load into table 'constituents_primaryaddress_stg_20210225_1023_8672' failed.  Check 'stl_load_errors' system table for details.
```

STL Load Error:
![image](https://user-images.githubusercontent.com/29580051/109175740-1a789380-7754-11eb-9b62-2ac4ae904277.png)

Seems like `alter_table=True` is not working as expected.

**Comment by shaunagm** [comment]
@elyse-weiss do you know if this is still an issue?

**Comment by elyse-weiss** [comment]
I don't unfortunately.

**Comment by shaunagm** [comment]
Okay, I'll close this for now then - if the issue gets spotted again we can re-open it.
