### ISSUE TITLE
Page Iterator in utilities

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#519]
Given the number of endpoints that include page number, it may be helpful to add a Page Iterator to utilities.

Here's a helpful Slack thread for context: https://tmc-parsons.slack.com/archives/C018N5ZCB99/p1620164384066600

**Comment by shaunagm** [comment]
Closing this in favor of #554 and #736 - I think we should create a page iterator utility and then expose it as a method in APIConnector class. This makes it easier for connectors based on APIConnector to use it, but also makes it importable for other connectors or use cases.
