### ISSUE TITLE
Add Pandas df vs Parsons table to documentation

### ISSUE THREAD

**Issue by thebbennett** [move-coop/parsons#531]
Stem from this Slack post: I may be missing this in the documentation, but would someone be willing to talk to me about the inspiration and reasoning behind the Parsons Table, why someone like me may want to move away from something like Pandas?

Soren's response: The main reason we use petl as the basis for the Parsons table instead of Pandas is because Pandas manages memory in a fundamentally different way, requiring more of a table to be loaded into memory in order to work on it. petl, on the other hand, streams data from a table whenever it's needed and only loads it in full during major transformations. That's the lazy loading Elyse mentioned above. This means that you can do a lot of rapid-fire ETL tasks without needing a huge amount of computing power, which helps save organizations a bunch of money on compute resources and do more work on large datasets using their own computers instead of having to spin up a bunch of EC2 instances on AWS or similar.

Elyse's response: @brittany can you put in a Parsons issue so we can add this to documentation? probably something we should add!

**Comment by Tomiiwa** [comment]
Hi, I would like to work on this documentation.

**Comment by Tomiiwa** [comment]
👍🏾
