### ISSUE TITLE
table.fillna_column relocates column

### ISSUE THREAD

**Issue by cmdelrio** [move-coop/parsons#537]
Hi!

I was conflicted about whether or not this issue was serious enough to report, but I noticed that the Table.fillna_column method not only fills empty values in a column, but it also reposition the column to the last position. For me, one line of code fixes the issue, but maybe it would cause issues in a more complicated script where column position is important. 
<img width="1349" alt="Screen Shot 2021-06-10 at 5 27 52 PM" src="https://user-images.githubusercontent.com/66973815/121706142-f5a5f300-ca9a-11eb-9445-53328ab64a55.png">

Thanks!
Cormac

**Comment by shaunagm** [comment]
Fixed by #603
