### ISSUE TITLE
Optionally Allow Modification of Allowable Multiple Choice Options in Insert Functions

### ISSUE THREAD

**Issue by SorenSpicknall** [move-coop/parsons#539]
The Airtable connector currently errors out if you try to insert values into a multiple select field that aren't allowed in the field definition. For some use cases, that would be desirable - you wouldn't want to accidentally insert a bunch of garbage into a tightly controlled field. But there should be an optional way to update the field with newly found values through the API, and that's not currently implemented in Parsons.

At first I thought that we'd have to fully implement new update functions, since the Python package we base the Parsons connector on doesn't implement anything from the Airtable metadata API, but I think there's a way to do this with a much smaller change. Looking at an example column, I found this documentation for changes to the allowable destination values:

>When creating or updating records, if  a  choice string does not exactly match an existing option, the request will fail with an INVALID_MULTIPLE_CHOICE_OPTIONS error unless the typecast parameter is enabled. If typecast is enabled, a new choice will be created if one does not exactly match.

Looking at the current code in Parsons, it seems like the typecast parameter just isn't implemented for the insert and batch_insert functions. This should be a pretty easy fix.

**Comment by thebbennett** [comment]
This is my very first contribution to an open source project and I followed [this guide](https://www.dataschool.io/how-to-contribute-on-github/) to set everything up. I may have mis read your issue so still down to talk @ our meeting. 

Don't know if/how you got a notification, but here's the PR: https://github.com/move-coop/parsons/pull/540
