### ISSUE TITLE
Add more helper methods and utilities to Parsons (and create standardized process for it)

### ISSUE THREAD

**Issue by schuyler1d** [move-coop/parsons#554]
_Note: Sky's original title was "Easy 'glue' connector script/format"._

There are a lot of "copy from X over to Y" uses in Parsons, and at MoveOn we found it useful to write a little 'generic' script that can take basically some JSON data and a link to credentials and shovel bits from one place to another place(s).

Here is our internal script:
https://gist.github.com/schuyler1d/6a5200214d43196e1d48cc9db136e720

It covers only the things that we, ourselves, needed as sources/destinations, but it would be great if we started building something like this in Parsons.  It could also pave the way for things like common From-A-to-B recipes, where A and B have specific schema mappings that we could save the same "created_at" => "date_created" kind of boring-work

**Comment by shaunagm** [comment]
Semi-addressed by #724 - changed the title of this issue to be a bit more expansive

**Comment by SorenSpicknall** [comment]
Old issue - community approach to utilities has evolved and spawned several new related issues
