### ISSUE TITLE
Issues installing Parsons on Python v3.9.x

### ISSUE THREAD

**Issue by ChrisC** [move-coop/parsons#575]
A lot of folks are reporting errors running Parsons upon first install with Python `v3.9.x` with errors related to loading to `psycopg`. Seems to be related to the Postgres `.DLL` files not being added to `$PATH`... some folks have found a workaround by installing `postgres` via homebrew. It would be great to improve the initial install step so that there isn't a need for extra steps if postgres is not installed locally.

**Comment by vignesh-ponraj** [comment]
This is so true, I can add a few points which helped me solve this.

- I used [pyenv-win](https://github.com/pyenv-win/pyenv-win) to use python 3.7 locally for this project.
- By following Vince's comment [here](https://tmc-parsons.slack.com/archives/C018N5ZCB99/p1631191183011400?thread_ts=1631161351.010700&cid=C018N5ZCB99) about psycopg install and postgres path
- While building docs, sometimes windows powershell doesn't recognize `make html` in which case, it was necessary to slightly modify it as `.\make html` and use it.

**Comment by shaunagm** [comment]
Closing this, as this guidance should be incorporated into the [installation guide](https://www.parsonsproject.org/pub/installation/r).
