### ISSUE TITLE
add a ControlShift connector

### ISSUE THREAD

**Issue by ChrisC** [move-coop/parsons#576]
For info on the platform, see: https://www.controlshiftlabs.com/

API documentation here: https://developers.controlshiftlabs.com/#json-api-endpoints

**Comment by tombola** [comment]
Hello @ChrisC - did you get anywhere with this?

I have been working with a Control Shift (and Action Network) in a current project, might be I could add something of value if you could fill me in on what you would want the connector to achieve.

btw, I got some **excellent** detailed help and support from @woodhull at Control Shift (including advice to check out this project), seems like running suggested features past their team could be a good way to jumpstart this, avoid steering people the wrong way with their integrations etc.

**Comment by tombola** [comment]
In case this helps anyone, here is a postman collection with a few of the control shift API requests that might be useful. [controlshift.postman_collection.json](https://gist.github.com/tombola/1d5d7b6d54ab24182533649ead5fd50a#file-controlshift-postman_collection-json-L516-L533)

Includes:

- Docs (links to CS docs per group request, plus headline description lifted from docs)
- Auth (config for the REST Oauth)
- Variables (stubs for your own instance), see ^^docs for details of auth env vars

Here is an (empty!) export of environment variables the collection will use for Oauth REST authentication:
[controlshift-auth.postman_environment.json](https://gist.github.com/tombola/76d45d8d428c99308f26fde5c8e4db02).

Suggest that for both the collection and environment just [edit the vars](https://gist.github.com/tombola/1d5d7b6d54ab24182533649ead5fd50a#file-controlshift-postman_collection-json-L516-L533) in json before importing.

**Comment by ChrisC** [comment]
Thanks @tombola ! We've completed an initial version of this in https://github.com/move-coop/parsons/pull/598 so closing this issue out. 

Def looking for more help covering the rest of the Oauth API but this should be a good start for anyone wanting to add to this connector
