### ISSUE TITLE
Resume work on Mobile Commons connector

### ISSUE THREAD

**Issue by ushayeruva** [move-coop/parsons#605]
Mobile Commons updated their API this year, so I'd love to help to help get this connector off the ground. I haven't done much parsons dev work before, but I'm a user and am fairly familiar with the MC API.

**Comment by cmdelrio** [comment]
Hello @ushayeruva! I recently started working with the MC API and want to package my work into parsons. I'm going to work on this over the next few weeks. Do you want to be involved at all?

**Comment by scmora** [comment]
Hey @cmdelrio were you able to publish or make progress on your Mobile Commons connector? One of our members is asking for this and I remember we talked a few months ago

**Comment by cmdelrio** [comment]
Hey @scmora, I haven't been able to finish this, but have made some solid progress. I wonder if they'd like to copy the code I've got into whatever project they're working on. What endpoints do they need?

**Comment by shaunagm** [comment]
Happy to help push this forward, whether that's by helping @cmdelrio to finish it, or helping @scmora or @ushayeruva to take over where Cormac left off. Cormac, what's your preference?

**Comment by scmora** [comment]
I no longer have a member asking for this so I will skip out! Thanks
everyone

**Comment by cmdelrio** [comment]
Hey @shaunagm I'm not sure I'm going to prioritize this in the next couple weeks. I'd be happy to pass off the issue to you, but I fear it will be difficult for you to test it since you don't have access to a MobileCommons instance. Moreover, I have a thread with MC from months ago about pagination that I'd need to share with you (in short, pagination needs to be handled differently for different GET enpoints - ANNOYING!). Maybe I can find the time to wrap up the pagination part if you want to write the unit tests? How does that sound?

**Comment by shaunagm** [comment]
I don't think this needs to be done in the next couple weeks, but I'm also happy to work with you to get this finished regardless of the timeline. I don't know how well I'd be able to write unit tests without access to a MobileCommons instance though. Maybe we can pair, at your convenience?

We're also planning to build pagination into the new API Connector (see #736) so it might make sense to coordinate that work with this, so we're not duplicating efforts. If you can share the thread with MC with me (and/or whoever ends up tackling the pagination utility) that would be super helpful.

**Comment by cmdelrio** [comment]
I will see if I can wrap up the non-unit testing part of this over the next couple weeks and then I'd be happy to pair on unit testing. 

As for pagination -- The thing about MC that is different is that it handles requests and responses in XML and HTML. I don't think the API Connector currently is compatible with those data formats.

**Comment by cmdelrio** [comment]
Hey @shaunagm! I wrapped up my work on this. Pagination for GET methods is working (such a headache) and I added a POST method for creating new mobile commons profiles. I wish I had time to add more, but hopefully this is a good starting point. Do you want to review what I've done so far and then we can co-work on unit testing together? I think I'm going to be pretty slammed next week, but maybe we can do the week after?

**Comment by shaunagm** [comment]
Closed by #896
