### ISSUE TITLE
Create PDI Functions Relating to Events, Event Invitations, and Contacts

### ISSUE THREAD

**Issue by cmdelrio** [move-coop/parsons#610]
The following end points are currently being added as functions to the PDI class
POST /calendars/{id}/events
GET /calendars
POST /eventActivities
GET /contacts
POST /contacts
POST /contacts/{contactId}/emails
POST /contacts/{contactId}/phones
POST /events/{eventid}/invitations
PUT /events/{eventid}/invitations/{id}
PUT /events/{id}

**Comment by cmdelrio** [comment]
Also:

GET /activities/{id}
POST /locations
GET /locations

**Comment by shaunagm** [comment]
Hi @cmdelrio! Did this get addressed via a PR? Maybe #654? It seems like there's some overlapping functionality but not everything got added.

If we should keep this open, can you let me know what priority this is for you?

**Comment by cmdelrio** [comment]
Yep! I think this is all good!
