### ISSUE TITLE
Request: Resolve incompatible dependencies with Google Composer (Airflow)

### ISSUE THREAD

**Issue by emily-flambe** [move-coop/parsons#616]
Parsons is currently incompatible with deployment in Google Composer, which is necessary to use parsons in Composer Airflow instances.

The specific offenders appear to be two packages:
- pyjwt (parsons requires 2.0.1, while no versions of Composer support pyjwt 2 or higher)
- google-cloud-storage (parsons requires 1.17.0, while Composer requires <2.0.0,>=1.30)

This is the error we get when attempting to install parsons in Composer:
![image](https://user-images.githubusercontent.com/47834372/151253814-041979fc-c21f-4ce4-930f-bd6190141223.png)

It would be amazing if we could get these dependencies resolved so that it would be possible to use parsons in Airflow using Google Composer. That would be a major unlock to enable all kinds of fancy orchestrated workflows.

(This request is similar to other existing issues requesting lighter-weight parsons to resolve similar compatibility issues, e.g. https://github.com/move-coop/parsons/issues/595)

**Comment by shaunagm** [comment]
I did a bit of digging and as far as I can tell, PyJWT is only being used by the Zoom connector: https://github.com/move-coop/parsons/blob/544c190e5c549b1aa882cd9f4bf5dff1be922915/parsons/zoom/zoom.py#L5  `google-cloud-storage` is, unsurprisingly, being used by several of the google connectors. 

We can test whether the connectors will work with the versions Google Composer needs—especially with GCS, the issue might just be that when the requirements were added, 1.17.0 was the most recent stable version.

But we might also want to think about this in the context of this issue: https://github.com/move-coop/parsons/issues/595 I imagine you're not even using the Zoom connector, so you shouldn't even need to download its dependencies. That leaves open the question of what to do about conflicting dependencies with a connector you *are* using, though.

**Comment by SorenSpicknall** [comment]
As @shaunagm mentioned, the best way to get around this will likely be to bump up the version number of the widely used google-cloud-storage dependency in Parsons (since our current version is behind and that change can likely be made in a backwards-compatible fashion), and then to ignore the other dependency issue by doing the following:

You can `pip install --no-deps parsons` in order to install Parsons without automatically loading any of its dependencies, and then individually `pip install` each of the packages in the Parsons [requirements.txt ](https://github.com/move-coop/parsons/blob/master/requirements.txt)_besides_ the failing PyJWT package.

So, I suggest opening a PR that bumps the google-cloud-storage version number and then using that workaround to avoid the PyJWT issue. Let me know if you have any questions about this approach!

**Comment by cmc333333** [comment]
I _think_ #632 will resolve this (though it depends on whether composer respects environment variables at build time). If not, there's another [composer-specific work around](https://cloud.google.com/composer/docs/how-to/using/installing-python-dependencies#install-local). The steps would be to:
1. Add `PARSONS_SKIP_IMPORT_ALL` as an environment variable to composer (per [these docs](https://move-coop.github.io/parsons/html/stable/index.html#minimizing-resource-utilization)). This'll prevent Parsons from trying to import everything (and causing dependency errors as a result). Note that it'll take a moment to rebuild composer's image.
1. Add `petl` and `simplejson` to composer's pypi dependencies (this'll also rebuild the image). These are Parsons dependencies that aren't [already present in composer](https://cloud.google.com/composer/docs/concepts/versioning/composer-versions#images).
1. In your dags directory, run `pip install -target . --no-deps parsons`. This'll download the `parsons` package into the current directory (without any of Parsons' dependencies). You can delete the dist-info and test directories (though it doesn't matter too much.)
1. Use `gsutil` to sync the files, e.g. from your dags directory: `gsutil cp -r . gs://[your-bucket]/dags`
1. Now your DAGs should be able to, e.g. `from parsons.actblue import ActBlue`

Super clunky, but I verified it works! I hope #632 works (but won't be able to test until it's in pypi).

**Comment by cmc333333** [comment]
Unfortunately, composer does not pay attention to environment variables when building images, so #632 doesn't resolve. The work around above should still work, though!

**Comment by shaunagm** [comment]
How dependencies work is [now documented on our website](https://www.parsonsproject.org/pub/friendly-dependencies/release/1). Closing this, but please feel free to let us know if there are other places we should be sharing this documentation.
