### ISSUE TITLE
Request: Add option to return results in JSON format

### ISSUE THREAD

**Issue by emily-flambe** [move-coop/parsons#617]
Our team has been exploring using Parsons to build custom source connectors in Airbyte. One major challenge we have faced is that Airbyte's SDK requires that data be returned in raw JSON format.

It would be super helpful if parsons had the ability to return data either as a Table object or as a JSON (eg, as an option when calling a function).

**Comment by hamzsait** [comment]
Parsons has the .to_json function. I changed the last line of the example script to save a .json file instead of a .csv file. Give it a try and see if it fits your use case. 

```
# Download the Census data from the Parsons GitHub repository
from parsons import GitHub
github = GitHub()
dummy_data = github.download_table('move-coop/parsons', 'docs/quickstart.csv')
assert dummy_data.num_rows == 1000  # Check that we got all 1,000 people

# Filter down to people with cell phones
people_with_cell_phones = dummy_data.select_rows(lambda row: row['is_cell'] == 'true')
assert people_with_cell_phones.num_rows == 498  # Check that we filtered down to our 498 people

# Extract only the columns we need (first name, last name, phone number)
people_with_cell_phones = people_with_cell_phones.cut('first_name', 'last_name', 'phone_number')
assert people_with_cell_phones.columns == ['first_name', 'last_name', 'phone_number'] # Check columns

# Output the list to a local JSON file
filename = people_with_cell_phones.to_json('test.json')  # filename will be the path to the local JSON file
```

**Comment by Jason94** [comment]
Hi @emilycogsdill. Did the `to_json` suggestion solve your use case? If saving to a file was not helpful, another option might be using the `to_dicts` method. In most cases an array of Python dictionary objects can be passed as JSON to an API.
