### ISSUE TITLE
VAN: logger error

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#63]
The error message `TypeError: string indices must be integers` comes up when using toggle_activist_code() , with the following:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/parsons/ngpvan/people.py in apply_response(self, id, response, id_type, contact_type_id, input_type_id, date_canvassed, result_code_id)
    435             logger.info(f'{id_type.upper()} {id} updated.')
    436         else:
--> 437             logger.info(f"{r[1]['errors'][0]['code']}: {r[1]['errors'][0]['text']}")
    438             raise ValueError(f"{r[1]['errors'][0]['text']}")
    439 

It looks like an API error from VAN is coming in as a string, but the logger in Parsons assumes it is a dictionary.

**Comment by jburchard** [comment]
@eliotst - You fixed this with #67, right?

**Comment by eliotst** [comment]
So, I think technically you fixed it in #52 .. #67 just tweaked how the error was being formatted. But, I believe this can be closed either way.
