### ISSUE TITLE
APIConnector get_request not passing params

### ISSUE THREAD

**Issue by ydamit** [move-coop/parsons#64]
On line 83 of utilities/api_connector.py :
`r = self.request(url, 'GET', params=None)`

But I think it should be:
`r = self.request(url, 'GET', params=params)`

Unless it intentionally isn't?

**Comment by jburchard** [comment]
You fixed this with PR #65, right?

**Comment by ydamit** [comment]
Yes, I just didn't connect it to this issue. I'll close now.
