### ISSUE TITLE
Switch dependency to newer simple-salesforce version 

### ISSUE THREAD

**Issue by cmdelrio** [move-coop/parsons#642]
I've been getting emails that salesforce is retiring old versions of their api. The Parsons simple-salesforce dependency is a super outdated version. It's not clear in their documentation which salesforce api version they use, but to be safe I think we need to update to a newer version.

**Comment by shaunagm** [comment]
@cmdelrio do those emails say when they old API will no longer be supported/will be retired? Trying to figure out how urgent a priority this is.

**Comment by cmdelrio** [comment]
May 22nd @shaunagm

**Comment by shaunagm** [comment]
Okay, that seems fairly high priority, then.

**Comment by bzupnick** [comment]
I believe this issue should also be closed as resolved!
