### ISSUE TITLE
Documentation of Parsons Table's to/from methods is incorrect

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#645]
If you compare the methods [in the code](https://github.com/move-coop/parsons/blob/master/parsons/etl/tofrom.py) to [the list in the docs](https://move-coop.github.io/parsons/html/table.html#from-parsons-table) it looks incorrect, specifically the 'from' table:

![Screenshot from 2022-03-22 18-03-08](https://user-images.githubusercontent.com/1179362/159583873-1359d6c5-ac17-429f-8b78-a6cbdc0a02e4.png)

Looking at the [corresponding docs page](https://github.com/move-coop/parsons/blob/master/docs/table.rst) I think the issue is just that some of the links are wrong - like `from_csv` somehow got used in place of `from_redshift` in the redshift row. Should be straightforward to fix, someone just needs to go through this carefully.

**Comment by shaunagm** [comment]
Yes, that would be great! Please reach out if you run into any trouble - our [docs on how to contribute to the docs](https://move-coop.github.io/parsons/html/contributing.html#documentation) are a little sparse but are hopefully helpful.

**Comment by 0saurabh0** [comment]
hey @shaunagm  i've successfully cloned it to my local system.

If i'm not wrong i just need to  replace  "**from_csv"**    to    "**from_redshift**"  ??

**Comment by shaunagm** [comment]
There's likely a few other mistakes in there. If you could go through the list of methods [in this code](https://github.com/move-coop/parsons/blob/master/parsons/etl/tofrom.py) and make sure they're all represented correctly in the two tables, with the [from Parsons table](https://move-coop.github.io/parsons/html/table.html#from-parsons-table) having the `to_*` methods and the [to Parsons table](https://move-coop.github.io/parsons/html/table.html#to-parsons-table) having the  `from_*` methods.

**Comment by 0saurabh0** [comment]
ok i'm on it.
