### ISSUE TITLE
Re-name Phone2Action to Capitol Canary

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#669]
"now is the time to retire the Phone2Action name and move forward with a new, more focused identity as we continue to transform how policy is won. Call us Capitol Canary."

we should probably re-name the connector? check out their API docs to confirm?

**Comment by shaunagm** [comment]
Moving my thoughts from Slack:

Proposal:
1 - create a new capitol canary class that P2A wraps around (so when P2A is eventually removed, it doesn't change capitol canary)
2 - when using the P2A, log a warning about the class being removed by a certain date, and instruction to switch to capitol canary
3 - the docs keep P2A but just as a brief statement that says its deprecated and you should use capitol canary
4 - at whatever the deprecation date is, we remove P2A connector and its associated docs, but leave a note on the capitol canary docs saying that it used to be the P2A connector and that you can see its docs in older versions of the docs

A PR to address this issue should handle steps 1-3, and then we can schedule a reminder near the deprecation date to do step 4.

**Comment by bzupnick** [comment]
@shaunagm should this get closed?

**Comment by shaunagm** [comment]
Yes! Thank you for helping keep the issue tracker up to date. And for the PR of course :)
