### ISSUE TITLE
Add Parsons Docker Image to Documentation

### ISSUE THREAD

**Issue by thebbennett** [move-coop/parsons#671]
Hello,

Occasionally someone will ask about docker image requirements to run Parsons. TMC maintains an image `movementcooperative/parsons` that could be opened to non-TMC members. If so, we should add a note about the usage of this image in the Parsons documentation. 

Cheers

**Comment by shaunagm** [comment]
There is [a link in the README](https://github.com/move-coop/parsons#docker-container) but it is not public, FYI.
