### ISSUE TITLE
paramiko error:  blowfish has been deprecated

### ISSUE THREAD

**Issue by loor12** [move-coop/parsons#683]
updated parsons package and when attempted to load `Redshift`, encountered this error in notebook: 

`CryptographyDeprecationWarning: Blowfish has been deprecated`
<img width="1207" alt="Screen Shot paramiko error" src="https://user-images.githubusercontent.com/46300917/167457122-bafca593-9974-4cd3-a85b-8f1b5a2f9fad.png">

Did some investigation and found this thread in the paramiko git. 
https://github.com/paramiko/paramiko/issues/2038

**Comment by thebbennett** [comment]
I am receiving the same error in a fresh virtual env instlal

**Comment by loor12** [comment]
oops I added the wrong link! https://github.com/paramiko/paramiko/issues/2038
