### ISSUE TITLE
Bug in Double application of Google Creds utility

### ISSUE THREAD

**Issue by ydamit** [move-coop/parsons#685]
The `setup_google_application_credentials()` utility is applied twice in any use of the `GoogleBigQuery` connector that uses `copy()` or any other method that also instantiates the `GoogleCloudStorage` class. 

Both of these classes make use of the `setup_google_application_credentials()` utility, which works fine the first time it's applied. The result under most conditions is that the `GOOGLE_APPLICATION_CREDENTIALS` env var is populated with the path to the temporary .json file holding the credentials.

The problem is that the _second_ time this is applied, a temporary file is created whose contents are merely the path to the _first_ temporary file, and the various clients involved don't know what to do with that. They try to parse that nested file path as a JSON string, and of course it throws an error.

I believe this might be most easily fixed by adding another condition to the `if` block to handle this edge case:
```
elif credentials.endswith('.json'):
    return True
```

**Comment by ydamit** [comment]
CC: @elyse-weiss and @zerlinac

**Comment by alxmrs** [comment]
I'm happy to take a look at this.

**Comment by SorenSpicknall** [comment]
Appears to be superseded by updated approach to passing auth information to BQ operations, but feel free to reopen if needed.
