### ISSUE TITLE
Bug in GoogleBigQuery Copy NoneType Handling

### ISSUE THREAD

**Issue by ydamit** [move-coop/parsons#691]
The [internal method](https://github.com/move-coop/parsons/blob/main/parsons/google/google_bigquery.py#L289), `_generate_schema()`, uses the Parsons Table method `get_columns_type_stats()` and parses it with the `BIGQUERY_TYPE_MAP` reference, rather than going through the whole `detect_data_type()` [process](https://github.com/move-coop/parsons/blob/main/parsons/databases/database/database.py#L140) the other database types use.

Unfortunately, `BIGQUERY_TYPE_MAP` doesn't account for columns with NoneType under certain circumstances. AS a result, `copy()` can fail if there are any non-string columns that also contain NoneType values.

It's possible that the better long-term solution would be to incorporate the BigQuery process. But a quick workaround is also possible that filters out NoneTypes before any application of `BIGQUERY_TYPE_MAP`

**Comment by ydamit** [comment]
@elyse-weiss & @zerlinac for awareness!

**Comment by SorenSpicknall** [comment]
Fixed in #695
