### ISSUE TITLE
Mobilize America connector needs refactoring

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#714]
As mentioned in https://github.com/move-coop/parsons/pull/708, the Mobilize connector has been partly broken for at least a little while. I've fixed some issues but plenty remain, largely endpoints no longer working because the Mobilize API has been changed (for example, `get_events_organization` is now supposed to hit `organizations/<org_id>/events`, instead of hitting `events/` with org_id passed in as a parameter (that old use was [deprecated](https://github.com/mobilizeamerica/api#deprecated-list-all-public-events).)

I recommend re-writing the connector to use the `APIConnector()` utility and double-checking all existing endpoints/updating tests.

## To Reproduce

To reproduce the changed endpoint issue, set up authentication to Mobilize (I'm using a staging account) and call `mobilize.get_events_organization(organization_id=your_org_id`. It should give you an error:

```
   line 66, in _request_paginate
    while r.json()['next']:
      KeyError: 'next'
```

At least for me, what's happening is that the old endpoint no longer returns the [expected format](https://github.com/mobilizeamerica/api#format) with 'next' and 'previous' parameters. Switching the endpoint to `organizations/<org_id>/events` gets it working.

## Your Environment

* Version of Parsons used (if you know): parsons installed from github main (so 0.19 but whatever the commit history is as of today, 7/9/2022)
* Environment name and version (e.g. Chrome 39, node.js 5.4): python 3.8.10
* Operating System and version (desktop or mobile): Ubuntu 20.04

## Priority
High priority - it seems pretty important to have a working Mobilize connector

**Comment by Jason94** [comment]
I'm going to start working on this one. I'll fix the endpoint that is broken (I looked and I think it's just the one) and update to use api connector under the hood.

**Comment by shaunagm** [comment]
Closing this. Mobilize still needs to be refactored to use APIConnector, but that's true of a number of working connectors which are all waiting on #736
