### ISSUE TITLE
More specific error when Table.from_csv() fails because of empty file

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#72]
I was running some code to pull down files from Google Cloud Storage, and move them Redshift. I received this error when running `Table.from_csv()`, and when I investigated, it looked like it was just an empty file. Would love for the logging to reflect that, if possible.

![image](https://user-images.githubusercontent.com/29580051/67959989-fa70a880-fbcf-11e9-8952-e8e9faf21e8d.png)

**Comment by jburchard** [comment]
Do you have an empty file that you could provide for testing?
