### ISSUE TITLE
Build Azure Class

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#73]
[here is some helpful code](https://gist.github.com/elyse-weiss/6bd367da334268b572aa9951446a3877) to get started with!

**Comment by elyse-weiss** [comment]
We talked about this today!

**Comment by pjsier** [comment]
I'm interested in working on this if it's available!

**Comment by elyse-weiss** [comment]
@pjsier go for it! Just updated the first comment with some code we have on hand that never made it into a formal class!
