### ISSUE TITLE
[Bug] Google Sheets initiation instructions insufficient

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#781]
## Detailed Description
The Google Sheets section includes direction on creating a service account. There is a key piece of information missing! The service account created -- [text]@[project].iam.gserviceaccount.com -- needs to be shared on any Google Sheets or Google Drive Folders being interacted with.

## Priority
High! I couldn't figure this out without asking others.

**Comment by ethyoo** [comment]
Does changing the code to automatically share a newly created file with the service account make sense?

We can get the service account's address with `credentials_dict['client_email']`

**Comment by elyse-weiss** [comment]
Sure! I think that would work.
