### ISSUE TITLE
Airtable Authentication set to change

### ISSUE THREAD

**Issue by cmdelrio** [move-coop/parsons#788]
Airtable is changing their authentication methods, moving away from API keys to OAuth integrations and Personal Access Tokens. API keys will not longer work after feb 1 2024. [Details](https://community.airtable.com/t5/announcements/new-api-capabilities-now-in-ga-and-upcoming-api-keys-deprecation/ba-p/141824?utm_ID=recdXE5vJZZ5vR0mh&utm_ID=recdXE5vJZZ5vR0mh&utm_source=lifecycle_team&utm_source=lifecycle_team&utm_medium=email&utm_medium=email&utm_campaign=it_ss_ss_api_deprecation&utm_campaign=it_ss_ss_api_depreciation&utm_content=email-blast_api_1a&utm_content=email-blast_api_key_users)

## Priority
Low. We have 1 year

**Comment by justicehaze** [comment]
As of today, Airtable does not allow users to create new API keys. I believe this makes new users of airtable and new bases, etc. Not work with our current Parsons connector. I think we should elevate this to a high priority. They will finally deprecate API keys in February of 2024.

**Comment by crayolakat** [comment]
I am interested in working on this task - assigning to myself

**Comment by mkrausse-ggtx** [comment]
@shaunagm looks like we can close this.

**Comment by crayolakat** [comment]
#866 was merged into the `major-release` branch but not yet the `main` branch. I'm actually wondering when it is planned to be merged into `main`?

**Comment by shaunagm** [comment]
Great question @crayolakat - it's about time for another release. I'll put that on my to-do list for the next week or so.

**Comment by shaunagm** [comment]
Sorry this is taking so long @crayolakat - turns out we weren't running the same tests on `major-release` so now we have to debug an issue. We should have the major release out on Monday (or late today if there's a real fast turnaround on the test failures we found) and we will improve the process so this hopefully doesn't happen again.

**Comment by codygordon** [comment]
This can be closed as completed, right?
