### ISSUE TITLE
Switch to using Black instead of/in addition to PyLint

### ISSUE THREAD

**Issue by shaunagm** [move-coop/parsons#791]
Manual linting is time-consuming for contributors. Switching to Black will allow contributors to lint with a single command.

Implementing this is going to involve a massive PR, since Black is very opinionated and will touch a ton of files. But it seems worth it in the long run.

**Comment by austinweisgrau** [comment]
Black by rigorous design cannot change the behavior of code at all, only the formatting. [See the docs on this topic](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#ast-before-and-after-formatting) for more.
