### ISSUE TITLE
[Feature/Addition] Census API

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#792]
People often rely on census data, and it's not always the easiest to navigate. A Parsons connector would be great to help individuals better grab the census data they need, more easily!

## Detailed Description
A list of all available APIs are here: https://www.census.gov/data/developers/data-sets.html

I imagine if we were able to get a class going with one, it'd be a great setup for folks to add additional APIs. I'd recommend perhaps starting with the American Community Survey. 

## Priority
Low - purely nice to have!

**Comment by elyse-weiss** [comment]
tagging in @IanRFerguson who may have some helpful code to contribute!

**Comment by schlich** [comment]
I teach a module in my data wrangling class i teach on the Census API.  I can def contribute to this :)

**Comment by AdriMichelson** [comment]
Would this have any functionality different from [cenpy](https://cenpy-devs.github.io/cenpy/) and [pigris](https://walker-data.com/pygris/)? @elyse-weiss

**Comment by Charlie-Kramer** [comment]
Hi, I'd be happy to take this on!

**Comment by shaunagm** [comment]
Thank you so much, @Charlie-Kramer! I've assigned the issue to you. I highly recommend taking a look at the [new connector guide](https://www.parsonsproject.org/pub/build-a-new-connector) before you get started - and I'm also happy to answer any questions you've got. :)

**Comment by shaunagm** [comment]
Hi Charlie, what's the status on this? Happy to help if you're stuck anywhere.

**Comment by Charlie-Kramer** [comment]
Oh hi! I thought I was all done? Not sure though am I missing something?

Looking at doing the request on the big query copy thing, have to re learn the relevant bits of big query first :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by shaunagm** [comment]
Oh yes #978! I'd remembered you'd done a connector but not that it was this one. I'll close this as complete :)

LMK if you need help with big query (or better yet feel free to post in Slack, plenty of big query users there)
