### ISSUE TITLE
[Bug] Zoom Credentials type change

### ISSUE THREAD

**Issue by stchessidy** [move-coop/parsons#849]
## Detailed Description
I was alerted to the fact that Zoom's JWT authentication type is going to be fully [deprecated](https://developers.zoom.us/docs/internal-apps/jwt-app-migration/) September 1st, 2023. They are recommending that folks switch over to using server to server oauth or an Oauth app. I have a couple of Zoom data syncs that I manage using the Zoom parsons class that will likely break if the authentication type is not updated.

## To Reproduce
See link above with announcement from Zoom

## Your Environment
N/A

## Additional Context
N/A

## Priority
Medium - because there is still 2 months to implement a fix before it breaks.

**Comment by stchessidy** [comment]
@IanRFerguson Hey Ian, @elyse-weiss asked me to tag you on this Parsons issue to see how long a fix might take.

**Comment by IanRFerguson** [comment]
> @IanRFerguson Hey Ian, @elyse-weiss asked me to tag you on this Parsons issue to see how long a fix might take.

hi hi, I'll put some time on my calendar to look today

**Comment by IanRFerguson** [comment]
## Current Status
* Adding to the working branch `ianferguson-zoom-auth`
* Updated the authentication to take account / client id + secret values ... this is passed via a `POST` response to Zoom's OAuth endpoint and the access token is stored to the object 

## Next Steps
I'm waiting for Personsified to up my access level in Zoom so I can test with users and meetings scopes to test the API

**Comment by Jason94** [comment]
@IanRFerguson I think functionally this is ready to be closed, but it looks like we missed some of the docs. The docstring for the constructor and the documentation on this page (https://move-coop.github.io/parsons/html/stable/zoom.html) are both out of date now. Could you submit a quick PR cleaning that up? I don't think we need to go in depth, but it might be worth mentioning that you just need to provide the ID and secret, and then point them to this page: https://developers.zoom.us/docs/internal-apps/s2s-oauth/

**Comment by IanRFerguson** [comment]
> @IanRFerguson I think functionally this is ready to be closed, but it looks like we missed some of the docs. The docstring for the constructor and the documentation on this page (https://move-coop.github.io/parsons/html/stable/zoom.html) are both out of date now. Could you submit a quick PR cleaning that up? I don't think we need to go in depth, but it might be worth mentioning that you just need to provide the ID and secret, and then point them to this page: https://developers.zoom.us/docs/internal-apps/s2s-oauth/

Totally, great flag! @sharinetmc can we chat through this when you have some free time?

**Comment by IanRFerguson** [comment]
Docs pushed
