### ISSUE TITLE
to_redshift() - max varchar length issues

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#85]
I personally have a number of syncs that use `to_redshift(if_exists='append')` and the call often fails because of varchar length. I am proposing a few changes:

- [ ] for any columns that are varchar, set the column to at lease varchar(100)
- [ ] for other varchar lengths, round up! so varchar(862) would become varchar(1000)

**Comment by jburchard** [comment]
@elyse-weiss - See PR #123  for the first step in this. Went the direction of making it more flexible.

**Comment by elyse-weiss** [comment]
@jburchard what do you see as next steps here? should we close?
