### ISSUE TITLE
Postgres support

### ISSUE THREAD

**Issue by JulieGoldberg** [move-coop/parsons#87]
It would be great if you could write tables to postgres servers as well as redshift. Being able to run queries from them and transfer data out of them would be a bonus.

**Comment by jburchard** [comment]
That's a really great suggestion. We are using `psycopg2` under the hood for Redshift, so it wouldn't add any additional dependencies either.

**Comment by dannyboy15** [comment]
@JulieGoldberg you should be able to connect to a postgres database using the `Redshift` class. For example:
```
from parsons import Redshift

pg = Redshift(username=pg_user, password=pg_pass, host=pg_url, ...)

data_table = pg.query("select * from my.table")
```

**Comment by dannyboy15** [comment]
As for the broader issue about adding postgres support, I agree that it's a great idea. However, I would recommend we restructure the codebase to avoid having duplicative code. I would suggest we create a `Postgres_Core` class where shared code can live. Then have `Redshift` and `Postgres` classes inherit from it and implement their unique methods.

**Comment by jburchard** [comment]
Interested in thoughts.

See PR #114
