### ISSUE TITLE
VAN apply_activist_code() logger text

### ISSUE THREAD

**Issue by mkwoods927** [move-coop/parsons#88]
When a script uses apply_activist_code a message comes through saying “Method deprecated. Use apply_activist_code() or remove_activist_code().” The AC still gets applied, but it’s a lot of scary red text when it happens for every record.![Screen Shot 2019-10-29 at 10.06.59 AM.png](https://images.zenhubusercontent.com/5d39fbd53f010b79423e5b0c/dec43851-e7b4-4c89-8795-16bea76593de)

**Comment by jburchard** [comment]
#89 PR resolves this.
