### ISSUE TITLE
[Feature/Addition] BigQuery get_columns_list() using information schema

### ISSUE THREAD

**Issue by elyse-weiss** [move-coop/parsons#909]
A BigQuery version of `Redshift.get_columns_list()` leveraging the information schema to save costs.

## Detailed Description
Idea here is to get same result as `get_columns_list()`, but without querying the table directly to save money in BigQuery!

## Context
TMC leverages this function a lot in Redshift, so we'd like it in BigQuery too!

## Possible Implementation
Shared above.

## Priority
High

CC: @shaunagm as this may be duplicative of other issues on bringing BigQuery up to parity with Redshift

**Comment by shaunagm** [comment]
@IanRFerguson @KasiaHinkson @sharinetmc - is this on your radar internally, are you hoping the wider Parsons community will tackle it?

**Comment by IanRFerguson** [comment]
> @IanRFerguson @KasiaHinkson @sharinetmc - is this on your radar internally, are you hoping the wider Parsons community will tackle it?

great question Shauna, we had not discussed it! I'll go ahead and knock it out before the end of the week
