### ISSUE TITLE
Documentation discrepancy regarding supported Python versions

### ISSUE THREAD

**Issue by mkrausse-ggtx** [move-coop/parsons#932]
The README.md file says "Parsons is only supported for Python 3.8-10." However on PyPI it says "Requires: Python >=3.7.0, <3.11.0"

Not sure which is correct.

**Comment by Jason94** [comment]
Here is the code from `setup.py`. It looks like PyPi is correct. However, this brings up that it's high time we move on from Python 3.7. It was sunset from receiving security updates a little while ago, and even Python 3.8 only has 10 months left. ([Source](https://devguide.python.org/versions/)).

@shaunagm Has there been conversation about bumping the Python version? In the meantime, I suppose we should fix the README?

**Comment by Jason94** [comment]
I guess that _allowing_ older versions isn't a problem. We should maybe consider adding 3.11, though. PETL (https://github.com/petl-developers/petl/blob/master/setup.py) still has Python 2.x listed as an allowed version! Although it does go up to 3.11.

I suppose the bigger issue with 3.7 is that it's still the Python version for the Dockerfile, but that's maybe a question for @willyraedy .

**Comment by shaunagm** [comment]
@willyraedy are you okay with us no longer officially supporting 3.7? Will changing it in the setup.py file cause any issues for your automatic builds etc?

Ideally TMC doesn't need 3.7 and we can solve this issue by adding 3.11 to the test suite, fixing any bugs that appear in the tests under 3.11, and then updating the documentation and setup.py to reflect that we now officially support 3.8-3.11. 

If TMC wants to keep 3.7 listed we can. The only downside is if there are bugs that only occur when running parsons under 3.7, in which case we ought to handle them.

**Comment by bmos** [comment]
I have been looking into 3.11 support.
At the moment, all the tests pass [except for one](https://github.com/bmos/parsons/actions/runs/8167109340/job/22326974373) and the error [appears to be](https://github.com/petl-developers/petl/pull/656/files) upstream.
I am [submitting a fix](https://github.com/petl-developers/petl/pull/656) there.

**Comment by bmos** [comment]
Pytest does not pass on 3.7.
https://github.com/move-coop/parsons/actions/runs/8274714031/job/22640505554

**Comment by jdw25** [comment]
I think this is now resolved with release of 3.2.0?

**Comment by shaunagm** [comment]
Yes, correct! Thanks for the flag @jdw25
