### ISSUE TITLE
PyPi Page Does Not Detect README.md

### ISSUE THREAD

**Issue by Jason94** [move-coop/parsons#944]
Currently the [Parsons PyPi page has a blank description](https://pypi.org/project/parsons/). This looks unprofessional, and might cause confusion for potential users trying to learn about Parsons. It's easy to configure the Python build system to use the GitHub readme file as the PyPi description.

If we add this code to our `setup.py` file, it should have the PyPi page use the README.md file as the description:
[https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/](https://packaging.python.org/en/latest/guides/making-a-pypi-friendly-readme/).

```python

# read the contents of your README file
from pathlib import Path
this_directory = Path(__file__).parent
long_description = (this_directory / "README.md").read_text()

setup(
    name='an_example_package',
    # other arguments omitted
    long_description=long_description,
    long_description_content_type='text/markdown'
)
```

**Comment by shaunagm** [comment]
This was fixed in the most recent release.
