### ISSUE TITLE
[Bug] Some methods listed in documentation are not present in Table class

### ISSUE THREAD

**Issue by lkesich** [move-coop/parsons#955]
## Detailed Description
The method rename_columns() is not present when the Table class is imported. Running `some_table.rename_columns(name_dict)` fails with the error "AttributeError: 'Table' object has no attribute 'rename_columns'."

I ran dir() to get a list of imported Table methods and noticed that rename_columns() is not listed. deduplicate() is also not listed despite appearing in the documentation.

The rename_columns() function works fine when copy/pasted from source code, just not as an attribute of the table object.

## To Reproduce

```
from parsons import Table
tbl = Table()
dir(tbl)
```
rename_columns and deduplicate are not present in listed methods.

## Your Environment

* Version of Parsons used: 1.0.0

## Priority
Low

**Comment by matthewkrausse** [comment]
Looks like you are using an older version of Parsons. The rename_columns method was added last month (by me). If you want to get the most recent version, you can install like this: `python -m pip install git+https://github.com/move-coop/parsons.git`.

Even the `pip install parsons` isn't up to date with that new change. 

This is what I get when running the same code in a fresh install using the git+... command.

`from parsons import Table
tbl = Table()
dir(tbl)`

Output:

['__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_index_count',
 '_prepend_dict',
 '_repr_html_',
 'add_column',
 'append_csv',
 'chunk',
 'coalesce_columns',
 'column_data',
 'columns',
 'concat',
 'convert_column',
 'convert_columns_to_str',
 'convert_table',
 'cut',
 'data',
 'deduplicate',
 'empty_column',
 'fill_column',
 'fillna_column',
 'first',
 'from_bigquery',
 'from_columns',
 'from_csv',
 'from_csv_string',
 'from_dataframe',
 'from_json',
 'from_postgres',
 'from_redshift',
 'from_s3_csv',
 'get_column_max_width',
 'get_column_types',
 'get_columns_type_stats',
 'get_normalized_column_name',
 'is_valid_table',
 'long_table',
 'map_and_coalesce_columns',
 'map_columns',
 'match_columns',
 'materialize',
 'materialize_to_file',
 'move_column',
 'num_rows',
 'reduce_rows',
 'remove_column',
 'remove_null_rows',
 'rename_column',
 'rename_columns',
 'row_data',
 'select_rows',
 'set_header',
 'sort',
 'stack',
 'table',
 'to_bigquery',
 'to_civis',
 'to_csv',
 'to_dataframe',
 'to_dicts',
 'to_gcs_csv',
 'to_html',
 'to_json',
 'to_petl',
 'to_postgres',
 'to_redshift',
 'to_s3_csv',
 'to_sftp_csv',
 'to_zip_csv',
 'unpack_dict',
 'unpack_list',
 'unpack_nested_columns_as_rows',
 'use_petl']

**Comment by lkesich** [comment]
Thank you! Those methods appear following install from GitHub. I appreciate your help.
